project_id = "njukrhmykrxqvjjvnotv"

[functions.verify-payment]
verify_jwt = false

[functions.admin-lessons]
verify_jwt = false

[functions.admin-dictionary]
verify_jwt = false

[functions.get-purchases]
verify_jwt = false
